name: maven-selenium-run

on:
  push:
    branches: [ main ]

jobs:
  maven-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install Google Chrome
        run: |
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven and run Selenium tests
        run: mvn clean verify